#!/usr/bin/env python3
"""Stage 1.4 full daily report builder.

This stage consumes every per-report summary generated by the Windows local LLM
orchestrator and creates two parallel artifacts:

1. a category-first daily integrated report using all report summaries
2. report-level insight atoms for novelty, minority views, contradictions, and
   new candidate discovery

It intentionally does not top-N filter report_summaries. Top-N selection can
still be used later for Deep Research prompts, but this file is the full daily
source of truth.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from report_orchestrator.config import load_config
from report_orchestrator.llm import LlmClient
from report_orchestrator.pipeline import category_slug, infer_summary_category
from report_orchestrator.text_processing import ensure_dir, read_json, write_json, write_text


NOVELTY_KEYWORDS = [
    "신규",
    "처음",
    "첫",
    "상향",
    "하향",
    "개시",
    "재개",
    "수주",
    "계약",
    "급증",
    "돌파",
    "최대",
    "사상",
    "턴어라운드",
    "레퍼런스",
    "공급",
    "승인",
    "정책",
]
NEGATIVE_KEYWORDS = ["리스크", "우려", "하향", "둔화", "부담", "감소", "압박", "실패", "취소"]
POSITIVE_KEYWORDS = ["상향", "개선", "성장", "호조", "수혜", "증가", "강세", "반등", "매력", "수주"]


def now_iso() -> str:
    return dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat()


def compact(value: Any) -> str:
    return " ".join(str(value or "").replace("\n", " ").split()).strip()


def clip(value: Any, limit: int) -> str:
    text = compact(value)
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 1)].rstrip() + "…"


def stable_hash(value: str, length: int = 10) -> str:
    return hashlib.sha1(value.encode("utf-8")).hexdigest()[:length]


def normalize_sentiment(value: Any) -> str:
    raw = compact(value).lower()
    if raw in {"bullish", "bearish", "neutral", "mixed"}:
        return raw
    if any(token in raw for token in ("긍정", "매수", "상승", "강세", "bull")):
        return "bullish"
    if any(token in raw for token in ("부정", "매도", "하락", "약세", "bear")):
        return "bearish"
    return "neutral"


def infer_direction(text: str, fallback: str = "neutral") -> str:
    normalized = compact(text)
    pos = sum(1 for keyword in POSITIVE_KEYWORDS if keyword in normalized)
    neg = sum(1 for keyword in NEGATIVE_KEYWORDS if keyword in normalized)
    if pos > neg:
        return "positive"
    if neg > pos:
        return "negative"
    sentiment = normalize_sentiment(fallback)
    if sentiment == "bullish":
        return "positive"
    if sentiment == "bearish":
        return "negative"
    return "neutral"


def score_novelty(text: str, *, entity_frequency: int = 1) -> float:
    normalized = compact(text)
    hits = sum(1 for keyword in NOVELTY_KEYWORDS if keyword in normalized)
    inverse_frequency_bonus = 0.18 if entity_frequency <= 1 else 0.08 if entity_frequency <= 3 else 0.0
    score = 0.28 + min(0.42, hits * 0.07) + inverse_frequency_bonus
    return round(max(0.05, min(0.95, score)), 3)


def score_conviction(text: str, evidence_count: int = 1) -> float:
    normalized = compact(text)
    number_bonus = min(0.2, len(re.findall(r"\d", normalized)) * 0.01)
    length_bonus = 0.12 if len(normalized) >= 80 else 0.04
    evidence_bonus = min(0.22, evidence_count * 0.055)
    return round(max(0.1, min(0.95, 0.28 + number_bonus + length_bonus + evidence_bonus)), 3)


def clean_list(values: Any, *, limit: int = 5, char_limit: int = 180) -> list[str]:
    if not isinstance(values, list):
        return []
    result: list[str] = []
    seen: set[str] = set()
    for value in values:
        text = clip(value, char_limit)
        key = text.lower()
        if not text or key in seen:
            continue
        seen.add(key)
        result.append(text)
        if len(result) >= limit:
            break
    return result


def compact_prompt_value(value: Any, *, list_limit: int = 5, string_limit: int = 180) -> Any:
    if isinstance(value, str):
        return clip(value, string_limit)
    if isinstance(value, (int, float, bool)) or value is None:
        return value
    if isinstance(value, list):
        return [
            compact_prompt_value(item, list_limit=list_limit, string_limit=string_limit)
            for item in value[:list_limit]
        ]
    if isinstance(value, dict):
        return {
            str(key): compact_prompt_value(item, list_limit=list_limit, string_limit=string_limit)
            for key, item in value.items()
            if item not in ("", None, [], {})
        }
    return clip(value, string_limit)


def brief_items(values: Any, *, limit: int = 3, char_limit: int = 120) -> list[str]:
    if not isinstance(values, list):
        return []
    result: list[str] = []
    for value in values:
        if isinstance(value, dict):
            text = (
                value.get("claim")
                or value.get("summary")
                or value.get("topic")
                or value.get("view")
                or value.get("name")
                or json.dumps(value, ensure_ascii=False)
            )
        else:
            text = value
        clipped = clip(text, char_limit)
        if clipped:
            result.append(clipped)
        if len(result) >= limit:
            break
    return result


def brief_company_mentions(values: Any, *, limit: int = 3) -> list[str]:
    if not isinstance(values, list):
        return []
    result: list[str] = []
    for value in values:
        if isinstance(value, dict):
            name = clip(value.get("name"), 40)
            view = clip(value.get("view") or value.get("rating") or "", 80)
            text = f"{name}: {view}" if view else name
        else:
            text = clip(value, 100)
        if text:
            result.append(text)
        if len(result) >= limit:
            break
    return result


def brief_atoms(values: Any, *, limit: int = 8, char_limit: int = 120) -> list[dict[str, Any]]:
    if not isinstance(values, list):
        return []
    result: list[dict[str, Any]] = []
    for atom in values:
        if not isinstance(atom, dict):
            continue
        result.append(
            {
                "type": atom.get("atom_type"),
                "entity": clip(atom.get("entity") or atom.get("title"), 40),
                "claim": clip(atom.get("claim"), char_limit),
                "report_id": atom.get("report_id"),
            }
        )
        if len(result) >= limit:
            break
    return result


def evidence_suffix(item: dict[str, Any]) -> str:
    evidence = item.get("evidence_report_ids") or item.get("evidence") or []
    if not isinstance(evidence, list) or not evidence:
        return ""
    return f" (근거: {', '.join(str(value) for value in evidence[:4])})"


def format_claim_item(item: Any, *, char_limit: int = 300) -> str:
    if not isinstance(item, dict):
        return clip(item, char_limit)
    claim = item.get("claim") or item.get("summary") or item.get("view") or item.get("name") or item.get("topic")
    if not claim:
        return clip(json.dumps(item, ensure_ascii=False), char_limit)
    text = clip(claim, char_limit)
    why = item.get("why_it_matters")
    if why:
        text += f" - 의미: {clip(why, 180)}"
    return text + evidence_suffix(item)


def format_grouped_claims(item: Any, *, char_limit: int = 300) -> list[str]:
    if not isinstance(item, dict) or not isinstance(item.get("items"), list):
        return [format_claim_item(item, char_limit=char_limit)]
    category = clip(item.get("category"), 60)
    rows: list[str] = []
    for child in item.get("items", [])[:3]:
        prefix = f"**{category}**: " if category else ""
        rows.append(prefix + format_claim_item(child, char_limit=char_limit))
    return rows


def format_contradiction_item(item: Any) -> str:
    if not isinstance(item, dict):
        return clip(item, 360)
    topic = clip(item.get("topic") or item.get("claim") or "쟁점", 80)
    side_a = clip(item.get("side_a") or item.get("bull_case") or item.get("positive_view"), 150)
    side_b = clip(item.get("side_b") or item.get("bear_case") or item.get("negative_view"), 150)
    if side_a or side_b:
        return f"**{topic}**: A) {side_a or 'N/A'} / B) {side_b or 'N/A'}{evidence_suffix(item)}"
    return format_claim_item(item, char_limit=360)


def format_grouped_contradictions(item: Any) -> list[str]:
    if not isinstance(item, dict) or not isinstance(item.get("items"), list):
        return [format_contradiction_item(item)]
    category = clip(item.get("category"), 60)
    rows: list[str] = []
    for child in item.get("items", [])[:3]:
        prefix = f"**{category}**: " if category else ""
        rows.append(prefix + format_contradiction_item(child))
    return rows


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build full daily report and insight atoms from all report summaries")
    parser.add_argument("--date", default=None, help="대상 날짜 (YYYY-MM-DD). 생략 시 최신 report_summaries 날짜")
    parser.add_argument("--run-date", default=None, help="실행일 (공통 파이프라인 호환용)")
    parser.add_argument("--effective-market-date", default=None, help="기준 거래일 (공통 파이프라인 호환용)")
    parser.add_argument("--run-id", default=None, help="run id (공통 파이프라인 호환용)")
    parser.add_argument("--config", default=None, help="local-report-orchestrator.json 경로")
    parser.add_argument("--detail", choices=["standard", "deep"], default=None, help="병합 상세도")
    parser.add_argument("--force", action="store_true", help="캐시 무시")
    parser.add_argument("--skip-llm", action="store_true", help="LLM 호출 없이 로컬 병합/atom만 생성")
    parser.add_argument("--llm-final", action="store_true", help="최종 일간 병합까지 LLM으로 수행. 기본은 카테고리 LLM 결과를 결정론적으로 합성")
    parser.add_argument("--llm-atoms", action="store_true", help="insight atom도 리포트별 LLM으로 보강")
    parser.add_argument("--merge-only", action="store_true", help="atom 파일은 읽기만 하고 full report만 생성")
    parser.add_argument("--atoms-only", action="store_true", help="insight atoms만 생성")
    parser.add_argument("--max-category-chars", type=int, default=15000, help="카테고리 병합 입력 배치 최대 문자 수")
    return parser.parse_args(argv)


def find_latest_summary_date(report_summaries_dir: Path) -> str:
    dates = [
        entry.name
        for entry in report_summaries_dir.iterdir()
        if entry.is_dir() and re.fullmatch(r"\d{4}-\d{2}-\d{2}", entry.name)
    ]
    if not dates:
        raise RuntimeError(f"report_summaries 날짜 디렉터리가 없습니다: {report_summaries_dir}")
    return sorted(dates)[-1]


def load_index_by_id(config: Any, date: str) -> dict[str, dict[str, Any]]:
    index_path = config.input_root / date / "index.json"
    rows = read_json(index_path, [])
    if not isinstance(rows, list):
        return {}
    return {str(row.get("id") or ""): row for row in rows if row.get("id")}


def load_report_summaries(config: Any, date: str) -> list[dict[str, Any]]:
    summary_dir = config.report_summaries_dir / date
    if not summary_dir.exists():
        raise RuntimeError(f"report_summaries 디렉터리가 없습니다: {summary_dir}")

    index_by_id = load_index_by_id(config, date)
    summaries: list[dict[str, Any]] = []
    for path in sorted(summary_dir.glob("report_*.json")):
        payload = read_json(path, {})
        report = payload.get("report")
        if not isinstance(report, dict):
            continue
        meta = payload.get("meta") if isinstance(payload.get("meta"), dict) else {}
        report_id = str(meta.get("report_id") or path.stem)
        index_meta = index_by_id.get(report_id, {})
        category = compact(index_meta.get("category") or report.get("category") or "")
        if not category:
            category = infer_summary_category(report)
        enriched = dict(report)
        enriched.update(
            {
                "report_id": report_id,
                "category": category,
                "source_path": str(path),
                "broker": compact(index_meta.get("broker") or index_meta.get("publisher") or report.get("publisher")),
                "ticker": index_meta.get("ticker"),
                "ticker_name": index_meta.get("ticker_name"),
                "broker_opinion": index_meta.get("opinion"),
                "broker_target_price": index_meta.get("target_price"),
            }
        )
        if not enriched.get("report_title"):
            enriched["report_title"] = compact(meta.get("report_title") or index_meta.get("title") or report_id)
        summaries.append(enriched)

    if not summaries:
        raise RuntimeError(f"읽을 수 있는 report summary가 없습니다: {summary_dir}")
    return summaries


def compact_report_for_merge(summary: dict[str, Any], *, char_limit: int = 500) -> dict[str, Any]:
    companies = []
    for company in summary.get("company_mentions") or []:
        if not isinstance(company, dict):
            continue
        companies.append(
            {
                "name": clip(company.get("name"), 50),
                "ticker": company.get("ticker"),
                "rating": company.get("rating", "unknown"),
                "target_price": company.get("target_price"),
                "key_points": clean_list(company.get("key_points"), limit=2, char_limit=110),
                "catalysts": clean_list(company.get("catalysts"), limit=1, char_limit=100),
                "risks": clean_list(company.get("risks"), limit=1, char_limit=100),
            }
        )
        if len(companies) >= 4:
            break

    return {
        "report_id": summary.get("report_id"),
        "title": clip(summary.get("report_title"), 120),
        "publisher": clip(summary.get("publisher") or summary.get("broker"), 50),
        "category": summary.get("category"),
        "sentiment": normalize_sentiment(summary.get("overall_sentiment")),
        "horizon": summary.get("time_horizon", "mid_term"),
        "core_summary": clip(summary.get("core_summary"), char_limit),
        "macro_view": clean_list(summary.get("macro_view"), limit=3, char_limit=150),
        "sector_view": clean_list(summary.get("sector_view"), limit=3, char_limit=150),
        "key_signals": clean_list(summary.get("key_signals"), limit=3, char_limit=150),
        "risks": clean_list(summary.get("risks"), limit=2, char_limit=140),
        "actionable_points": clean_list(summary.get("actionable_points"), limit=2, char_limit=140),
        "company_mentions": companies,
    }


def split_batches(items: list[dict[str, Any]], max_chars: int) -> list[list[dict[str, Any]]]:
    batches: list[list[dict[str, Any]]] = []
    current: list[dict[str, Any]] = []
    current_chars = 0
    for item in items:
        size = len(json.dumps(item, ensure_ascii=False))
        if current and current_chars + size > max_chars:
            batches.append(current)
            current = []
            current_chars = 0
        current.append(item)
        current_chars += size
    if current:
        batches.append(current)
    return batches


def local_category_merge(category: str, summaries: list[dict[str, Any]]) -> dict[str, Any]:
    sentiment_counts = Counter(normalize_sentiment(item.get("overall_sentiment")) for item in summaries)
    overall = sentiment_counts.most_common(1)[0][0] if sentiment_counts else "neutral"
    pools: dict[str, list[str]] = defaultdict(list)
    companies: Counter[str] = Counter()
    report_refs = []
    for item in summaries:
        report_refs.append(
            {
                "report_id": item.get("report_id"),
                "title": clip(item.get("report_title"), 100),
                "sentiment": normalize_sentiment(item.get("overall_sentiment")),
            }
        )
        pools["summaries"].append(clip(item.get("core_summary"), 220))
        for field in ("macro_view", "sector_view", "key_signals", "risks", "actionable_points"):
            pools[field].extend(clean_list(item.get(field), limit=5, char_limit=160))
        for company in item.get("company_mentions") or []:
            if isinstance(company, dict) and company.get("name"):
                companies[compact(company["name"])] += 1

    def top_unique(field: str, limit: int = 7) -> list[str]:
        counter = Counter(text for text in pools[field] if text)
        return [text for text, _count in counter.most_common(limit)]

    company_mentions = [
        {"name": name, "mention_count": count}
        for name, count in companies.most_common(12)
    ]
    consensus = top_unique("key_signals", 6) or top_unique("summaries", 4)
    risks = top_unique("risks", 6)

    return {
        "category": category,
        "report_count": len(summaries),
        "overall_sentiment": overall,
        "market_summary": clip(" ".join(top_unique("summaries", 3)), 900),
        "consensus_view": consensus,
        "minority_view": top_unique("actionable_points", 4),
        "contradictions": [],
        "investment_hypothesis": clip(" / ".join(consensus[:3]), 500),
        "macro_view": top_unique("macro_view", 7),
        "sector_view": top_unique("sector_view", 7),
        "key_signals": top_unique("key_signals", 8),
        "risks": risks,
        "company_mentions": company_mentions,
        "actionable_points": top_unique("actionable_points", 7),
        "source_reports": report_refs,
        "merge_method": "local",
    }


def llm_category_merge(
    client: LlmClient,
    *,
    category: str,
    summaries: list[dict[str, Any]],
    max_tokens: int,
    retry_attempts: int,
) -> dict[str, Any]:
    prompt_summaries = [compact_report_for_merge(item) for item in summaries]
    messages = [
        {
            "role": "system",
            "content": (
                f"너는 '{category}' 카테고리 리포트 {len(summaries)}건을 하나의 카테고리 리포트로 병합하는 금융 분석가다. "
                "입력된 모든 report_id를 고려하되 단순 평균을 내지 말고 컨센서스, 소수 의견, 충돌, 신규 후보, 실행 체크포인트를 분리하라. "
                "반드시 JSON 객체만 출력하라. 모든 주장에는 가능한 report_id evidence를 붙여라."
            ),
        },
        {
            "role": "user",
            "content": json.dumps(
                {
                    "task": "full_category_merge_all_reports",
                    "category": category,
                    "report_count": len(summaries),
                    "required_schema": {
                        "category": category,
                        "report_count": len(summaries),
                        "overall_sentiment": "bullish|bearish|neutral|mixed",
                        "market_summary": "",
                        "consensus_view": [{"claim": "", "evidence_report_ids": []}],
                        "minority_view": [{"claim": "", "why_it_matters": "", "evidence_report_ids": []}],
                        "contradictions": [{"topic": "", "side_a": "", "side_b": "", "evidence_report_ids": []}],
                        "investment_hypothesis": "",
                        "macro_view": [],
                        "sector_view": [],
                        "key_signals": [],
                        "risks": [],
                        "company_mentions": [{"name": "", "view": "", "evidence_report_ids": []}],
                        "actionable_points": [],
                    },
                    "report_summaries": prompt_summaries,
                },
                ensure_ascii=False,
            ),
        },
    ]
    result = client.complete_json(
        messages=messages,
        temperature=0.1,
        max_tokens=max_tokens,
        retry_attempts=retry_attempts,
    )
    payload = result.payload
    payload.setdefault("category", category)
    payload.setdefault("report_count", len(summaries))
    payload["merge_method"] = "llm"
    return payload


def merge_category(
    client: LlmClient | None,
    *,
    category: str,
    summaries: list[dict[str, Any]],
    max_chars: int,
    max_tokens: int,
    retry_attempts: int,
    skip_llm: bool,
) -> dict[str, Any]:
    compacted = [compact_report_for_merge(item) for item in summaries]
    batches = split_batches(compacted, max_chars)

    if skip_llm or client is None:
        return local_category_merge(category, summaries)

    try:
        if len(batches) <= 1:
            return llm_category_merge(
                client,
                category=category,
                summaries=summaries,
                max_tokens=max_tokens,
                retry_attempts=retry_attempts,
            )

        sub_views: list[dict[str, Any]] = []
        by_id = {item["report_id"]: item for item in summaries}
        for batch in batches:
            batch_ids = [item.get("report_id") for item in batch]
            batch_summaries = [by_id[report_id] for report_id in batch_ids if report_id in by_id]
            sub_views.append(
                llm_category_merge(
                    client,
                    category=f"{category} 배치",
                    summaries=batch_summaries,
                    max_tokens=max_tokens,
                    retry_attempts=retry_attempts,
                )
            )
        final_view = llm_category_merge(
            client,
            category=f"{category} 통합",
            summaries=[
                {
                    "report_id": f"{category_slug(category)}_batch_{index + 1}",
                    "report_title": view.get("category", category),
                    "publisher": "stage1.4",
                    "category": category,
                    "overall_sentiment": view.get("overall_sentiment", "neutral"),
                    "core_summary": view.get("market_summary", ""),
                    "macro_view": view.get("macro_view", []),
                    "sector_view": view.get("sector_view", []),
                    "key_signals": view.get("key_signals", []),
                    "risks": view.get("risks", []),
                    "actionable_points": view.get("actionable_points", []),
                    "company_mentions": view.get("company_mentions", []),
                }
                for index, view in enumerate(sub_views)
            ],
            max_tokens=max_tokens,
            retry_attempts=retry_attempts,
        )
        final_view["sub_batch_count"] = len(sub_views)
        return final_view
    except Exception as error:  # noqa: BLE001
        fallback = local_category_merge(category, summaries)
        fallback["merge_method"] = "local_after_llm_error"
        fallback["llm_error"] = clip(str(error), 500)
        return fallback


def entity_frequency(summaries: list[dict[str, Any]]) -> Counter[str]:
    counter: Counter[str] = Counter()
    for summary in summaries:
        for company in summary.get("company_mentions") or []:
            if isinstance(company, dict) and company.get("name"):
                counter[compact(company["name"])] += 1
        for value in clean_list(summary.get("sector_view"), limit=5, char_limit=60):
            counter[value] += 1
    return counter


def build_local_atoms(summary: dict[str, Any], frequencies: Counter[str]) -> list[dict[str, Any]]:
    report_id = str(summary.get("report_id"))
    title = summary.get("report_title")
    category = summary.get("category")
    sentiment = normalize_sentiment(summary.get("overall_sentiment"))
    atoms: list[dict[str, Any]] = []

    def add_atom(atom_type: str, claim: str, *, entity: str = "", evidence: list[str] | None = None) -> None:
        claim_text = clip(claim, 360)
        if not claim_text:
            return
        entity_text = entity or clip(title, 80)
        freq = frequencies.get(entity_text, 1)
        atom_key = f"{report_id}|{atom_type}|{claim_text}"
        atoms.append(
            {
                "atom_id": f"{report_id}_{stable_hash(atom_key, 8)}",
                "report_id": report_id,
                "title": title,
                "publisher": summary.get("publisher") or summary.get("broker"),
                "category": category,
                "atom_type": atom_type,
                "entity": entity_text,
                "claim": claim_text,
                "direction": infer_direction(claim_text, sentiment),
                "horizon": summary.get("time_horizon", "mid_term"),
                "novelty_score": score_novelty(claim_text, entity_frequency=freq),
                "conviction_score": score_conviction(claim_text, len(evidence or [])),
                "evidence": evidence or [report_id],
                "portfolio_relevance": clean_list(summary.get("portfolio_relevance"), limit=3, char_limit=140),
                "source_fields": [],
            }
        )

    add_atom("thesis", summary.get("core_summary", ""), evidence=[report_id])
    for signal in clean_list(summary.get("key_signals"), limit=3, char_limit=240):
        add_atom("catalyst", signal, evidence=[report_id])
    for risk in clean_list(summary.get("risks"), limit=2, char_limit=240):
        add_atom("risk", risk, evidence=[report_id])
    for company in summary.get("company_mentions") or []:
        if not isinstance(company, dict) or not company.get("name"):
            continue
        name = compact(company["name"])
        key_points = clean_list(company.get("key_points"), limit=2, char_limit=180)
        catalysts = clean_list(company.get("catalysts"), limit=1, char_limit=180)
        risks = clean_list(company.get("risks"), limit=1, char_limit=160)
        claim = " / ".join(key_points + catalysts + risks)
        atom_type = "new_candidate" if summary.get("ticker_name") or any(k in claim for k in NOVELTY_KEYWORDS) else "company_view"
        add_atom(atom_type, claim or f"{name} 관련 리포트 관찰", entity=name, evidence=[report_id])

    deduped: list[dict[str, Any]] = []
    seen: set[str] = set()
    for atom in sorted(atoms, key=lambda item: (item["novelty_score"], item["conviction_score"]), reverse=True):
        key = f"{atom['atom_type']}|{atom['entity']}|{atom['claim'][:80]}"
        if key in seen:
            continue
        seen.add(key)
        deduped.append(atom)
        if len(deduped) >= 7:
            break
    return deduped


def llm_atoms_for_report(client: LlmClient, summary: dict[str, Any], retry_attempts: int) -> list[dict[str, Any]]:
    report_id = summary.get("report_id")
    messages = [
        {
            "role": "system",
            "content": (
                "너는 증권사 리포트 요약에서 투자 판단용 insight atom을 추출하는 분석기다. "
                "요약을 다시 쓰지 말고 claim 단위로 쪼개라. 반드시 JSON 객체만 출력하라."
            ),
        },
        {
            "role": "user",
            "content": json.dumps(
                {
                    "task": "extract_report_insight_atoms",
                    "report_id": report_id,
                    "required_schema": {
                        "atoms": [
                            {
                                "atom_type": "thesis|catalyst|risk|new_candidate|contradiction|portfolio_impact",
                                "entity": "",
                                "claim": "",
                                "direction": "positive|negative|neutral|mixed",
                                "horizon": "short_term|mid_term|long_term",
                                "novelty_score": 0.0,
                                "conviction_score": 0.0,
                                "evidence": [],
                            }
                        ]
                    },
                    "report_summary": compact_report_for_merge(summary, char_limit=700),
                },
                ensure_ascii=False,
            ),
        },
    ]
    result = client.complete_json(
        messages=messages,
        temperature=0.1,
        max_tokens=2200,
        retry_attempts=retry_attempts,
    )
    raw_atoms = result.payload.get("atoms", [])
    atoms: list[dict[str, Any]] = []
    if not isinstance(raw_atoms, list):
        return atoms
    for raw in raw_atoms[:7]:
        if not isinstance(raw, dict):
            continue
        claim = clip(raw.get("claim"), 360)
        if not claim:
            continue
        atom_key = f"{report_id}|{raw.get('atom_type')}|{claim}"
        atoms.append(
            {
                "atom_id": f"{report_id}_{stable_hash(atom_key, 8)}",
                "report_id": report_id,
                "title": summary.get("report_title"),
                "publisher": summary.get("publisher") or summary.get("broker"),
                "category": summary.get("category"),
                "atom_type": compact(raw.get("atom_type") or "thesis"),
                "entity": clip(raw.get("entity") or summary.get("report_title"), 80),
                "claim": claim,
                "direction": compact(raw.get("direction") or infer_direction(claim, summary.get("overall_sentiment"))),
                "horizon": compact(raw.get("horizon") or summary.get("time_horizon") or "mid_term"),
                "novelty_score": max(0.0, min(1.0, float(raw.get("novelty_score") or score_novelty(claim)))),
                "conviction_score": max(0.0, min(1.0, float(raw.get("conviction_score") or score_conviction(claim)))),
                "evidence": raw.get("evidence") if isinstance(raw.get("evidence"), list) else [report_id],
                "portfolio_relevance": clean_list(summary.get("portfolio_relevance"), limit=3, char_limit=140),
                "source_fields": ["llm_atoms"],
            }
        )
    return atoms


def build_insight_atoms(
    summaries: list[dict[str, Any]],
    *,
    client: LlmClient | None,
    llm_atoms: bool,
    retry_attempts: int,
) -> dict[str, Any]:
    frequencies = entity_frequency(summaries)
    atoms: list[dict[str, Any]] = []
    failures: list[dict[str, str]] = []
    for summary in summaries:
        local_atoms = build_local_atoms(summary, frequencies)
        if client and llm_atoms:
            try:
                report_atoms = llm_atoms_for_report(client, summary, retry_attempts)
                atoms.extend(report_atoms or local_atoms)
            except Exception as error:  # noqa: BLE001
                failures.append({"report_id": str(summary.get("report_id")), "error": clip(str(error), 300)})
                atoms.extend(local_atoms)
        else:
            atoms.extend(local_atoms)

    atom_by_id = {atom["atom_id"]: atom for atom in atoms}
    deduped = list(atom_by_id.values())
    by_type = Counter(atom.get("atom_type", "unknown") for atom in deduped)
    by_category = Counter(atom.get("category", "기타") for atom in deduped)
    top_atoms = sorted(
        deduped,
        key=lambda item: (item.get("novelty_score", 0) * 0.55 + item.get("conviction_score", 0) * 0.45),
        reverse=True,
    )[:40]
    new_candidates = [
        atom
        for atom in top_atoms
        if atom.get("atom_type") in {"new_candidate", "company_view"} and atom.get("direction") in {"positive", "mixed"}
    ][:20]
    risks = [atom for atom in top_atoms if atom.get("atom_type") == "risk" or atom.get("direction") == "negative"][:20]

    return {
        "schemaVersion": 1,
        "generated_at": now_iso(),
        "method": "llm_atoms" if llm_atoms and client else "local_atoms_from_report_summaries",
        "atom_count": len(deduped),
        "source_report_count": len(summaries),
        "type_counts": dict(by_type),
        "category_counts": dict(by_category),
        "top_atoms": top_atoms,
        "new_candidates": new_candidates,
        "risk_atoms": risks,
        "atoms": deduped,
        "failures": failures,
    }


def local_final_merge(date: str, category_views: dict[str, dict[str, Any]], atom_payload: dict[str, Any]) -> dict[str, Any]:
    report_count = sum(int(view.get("report_count") or 0) for view in category_views.values())
    sentiment_counter = Counter(view.get("overall_sentiment", "neutral") for view in category_views.values())
    top_atoms = atom_payload.get("top_atoms", [])[:12]
    new_candidates = atom_payload.get("new_candidates", [])[:10]
    risk_atoms = atom_payload.get("risk_atoms", [])[:10]
    return {
        "date": date,
        "report_count": report_count,
        "overall_sentiment": sentiment_counter.most_common(1)[0][0] if sentiment_counter else "neutral",
        "one_line": clip(" / ".join(view.get("market_summary", "") for view in category_views.values()), 500),
        "consensus": [
            {"category": category, "items": view.get("consensus_view", [])[:4]}
            for category, view in category_views.items()
        ],
        "minority_views": [
            {"category": category, "items": view.get("minority_view", [])[:3]}
            for category, view in category_views.items()
            if view.get("minority_view")
        ],
        "contradictions": [
            {"category": category, "items": view.get("contradictions", [])[:3]}
            for category, view in category_views.items()
            if view.get("contradictions")
        ],
        "top_insight_atoms": top_atoms,
        "new_candidates": new_candidates,
        "risk_atoms": risk_atoms,
        "category_views": category_views,
        "merge_method": "local",
    }


def llm_final_merge(
    client: LlmClient,
    *,
    date: str,
    category_views: dict[str, dict[str, Any]],
    atom_payload: dict[str, Any],
    max_tokens: int,
    retry_attempts: int,
) -> dict[str, Any]:
    compact_categories = {
        category: {
            "report_count": view.get("report_count"),
            "overall_sentiment": view.get("overall_sentiment"),
            "market_summary": clip(view.get("market_summary"), 260),
            "consensus_view": brief_items(view.get("consensus_view", []), limit=3, char_limit=120),
            "minority_view": brief_items(view.get("minority_view", []), limit=2, char_limit=110),
            "contradictions": brief_items(view.get("contradictions", []), limit=2, char_limit=110),
            "investment_hypothesis": clip(view.get("investment_hypothesis"), 220),
            "key_signals": brief_items(view.get("key_signals", []), limit=3, char_limit=100),
            "risks": brief_items(view.get("risks", []), limit=2, char_limit=100),
            "company_mentions": brief_company_mentions(view.get("company_mentions", []), limit=3),
            "actionable_points": brief_items(view.get("actionable_points", []), limit=2, char_limit=100),
        }
        for category, view in category_views.items()
    }
    messages = [
        {
            "role": "system",
            "content": (
                "너는 하루치 증권사 리포트 전체를 통합하는 CIO 보좌역이다. "
                "모든 카테고리 뷰와 insight atom을 이용해 해당일자 통합 요약 리포트를 만든다. "
                "평균적인 시장 코멘트로 뭉개지 말고 컨센서스, 소수의견, 충돌, 신규 후보, 포트폴리오 영향 슬롯을 분리하라. "
                "반드시 JSON 객체만 출력하라."
            ),
        },
        {
            "role": "user",
            "content": json.dumps(
                {
                    "task": "daily_full_integrated_report",
                    "date": date,
                    "required_schema": {
                        "date": date,
                        "report_count": 0,
                        "overall_sentiment": "bullish|bearish|neutral|mixed",
                        "one_line": "",
                        "today_consensus": [],
                        "minority_views": [],
                        "contradictions": [],
                        "new_candidates": [],
                        "portfolio_relevant_ideas": [],
                        "risk_watch": [],
                        "ignore_or_deprioritize": [],
                        "deep_research_questions": [],
                        "category_summaries": [],
                    },
                    "category_views": compact_categories,
                    "insight_atoms": {
                        "top_atoms": brief_atoms(atom_payload.get("top_atoms", []), limit=8, char_limit=120),
                        "new_candidates": brief_atoms(atom_payload.get("new_candidates", []), limit=6, char_limit=120),
                        "risk_atoms": brief_atoms(atom_payload.get("risk_atoms", []), limit=5, char_limit=120),
                    },
                },
                ensure_ascii=False,
            ),
        },
    ]
    result = client.complete_json(
        messages=messages,
        temperature=0.1,
        max_tokens=max_tokens,
        retry_attempts=retry_attempts,
    )
    payload = result.payload
    payload.setdefault("date", date)
    payload["merge_method"] = "llm"
    return payload


def render_markdown(date: str, final_report: dict[str, Any], category_views: dict[str, dict[str, Any]], atom_payload: dict[str, Any]) -> str:
    lines = [
        f"# {date} Full Daily Report",
        "",
        f"- 리포트 수: {final_report.get('report_count') or sum(int(v.get('report_count') or 0) for v in category_views.values())}",
        f"- 병합 방식: {final_report.get('merge_method', 'unknown')}",
        f"- 전체 분위기: {final_report.get('overall_sentiment', 'neutral')}",
        "",
        "## 한 줄 진단",
        f"- {final_report.get('one_line') or final_report.get('market_summary') or 'N/A'}",
        "",
        "## 오늘의 컨센서스",
    ]
    consensus = final_report.get("today_consensus") or final_report.get("consensus") or []
    if isinstance(consensus, list):
        for item in consensus[:10]:
            for row in format_grouped_claims(item, char_limit=300):
                lines.append(f"- {row}")
    lines.extend(["", "## 소수 의견 / 비컨센서스"])
    minority = final_report.get("minority_views") or []
    if isinstance(minority, list):
        for item in minority[:10]:
            for row in format_grouped_claims(item, char_limit=300):
                lines.append(f"- {row}")
    lines.extend(["", "## 충돌하는 시각"])
    contradictions = final_report.get("contradictions") or []
    if isinstance(contradictions, list):
        for item in contradictions[:10]:
            for row in format_grouped_contradictions(item):
                lines.append(f"- {row}")
    lines.extend(["", "## 신규 후보 / 종목 아이디어"])
    candidates = final_report.get("new_candidates") or atom_payload.get("new_candidates", [])
    if isinstance(candidates, list):
        for item in candidates[:12]:
            if isinstance(item, dict):
                label = item.get("entity") or item.get("name") or item.get("claim")
                claim = item.get("claim") or item.get("view") or item
                lines.append(f"- **{clip(label, 80)}**: {clip(claim, 260)}")
            else:
                lines.append(f"- {clip(item, 320)}")
    lines.extend(["", "## 리스크 Watch"])
    risks = final_report.get("risk_watch") or final_report.get("risk_atoms") or atom_payload.get("risk_atoms", [])
    if isinstance(risks, list):
        for item in risks[:12]:
            if isinstance(item, dict):
                lines.append(f"- {clip(item.get('entity'), 80)}: {clip(item.get('claim'), 260)}")
            else:
                lines.append(f"- {clip(item, 320)}")
    lines.extend(["", "## 카테고리별 통합"])
    for category, view in category_views.items():
        lines.extend([
            "",
            f"### {category} ({view.get('report_count', 0)}건)",
            f"- {clip(view.get('market_summary'), 500)}",
        ])
        for signal in (view.get("key_signals") or [])[:5]:
            lines.append(f"- {clip(signal, 220)}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    if args.detail:
        os.environ["REPORT_ORCHESTRATOR_DETAIL"] = args.detail
    config = load_config(args.config)
    date = args.effective_market_date or args.date or find_latest_summary_date(config.report_summaries_dir)

    summaries = load_report_summaries(config, date)
    state_dir = config.repo_root / "data" / "analysis-state" / date
    daily_dir = config.repo_root / "knowledge" / "daily"
    full_dir = state_dir / "full-report"
    ensure_dir(full_dir)

    client: LlmClient | None = None
    if not args.skip_llm:
        client = LlmClient(config)

    atoms_path = state_dir / "stage1-4-insight-atoms.json"
    if args.merge_only and atoms_path.exists() and not args.force:
        atom_payload = read_json(atoms_path, {})
    else:
        atom_payload = build_insight_atoms(
            summaries,
            client=client,
            llm_atoms=args.llm_atoms and not args.skip_llm,
            retry_attempts=config.merge_retry_attempts,
        )
        write_json(atoms_path, atom_payload)

    if args.atoms_only:
        print(str(atoms_path))
        return 0

    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for summary in summaries:
        groups[str(summary.get("category") or infer_summary_category(summary))].append(summary)

    category_views: dict[str, dict[str, Any]] = {}
    by_category_dir = full_dir / "by_category"
    ensure_dir(by_category_dir)
    for category, items in sorted(groups.items()):
        out_path = by_category_dir / f"{category_slug(category)}.json"
        if out_path.exists() and not args.force:
            cached = read_json(out_path, {})
            cached_meta = cached.get("meta") if isinstance(cached.get("meta"), dict) else {}
            if isinstance(cached.get("category_view"), dict) and cached_meta.get("skip_llm") == args.skip_llm:
                category_views[category] = cached["category_view"]
                continue
        view = merge_category(
            client,
            category=category,
            summaries=items,
            max_chars=args.max_category_chars,
            max_tokens=config.category_merge_max_tokens,
            retry_attempts=config.merge_retry_attempts,
            skip_llm=args.skip_llm,
        )
        view["report_count"] = len(items)
        category_views[category] = view
        write_json(
            out_path,
            {
                "meta": {
                    "schemaVersion": 1,
                    "generated_at": now_iso(),
                    "date": date,
                    "category": category,
                    "report_count": len(items),
                    "model": config.model if not args.skip_llm else "local",
                    "skip_llm": args.skip_llm,
                },
                "category_view": view,
            },
        )

    if args.skip_llm or client is None or not args.llm_final:
        final_report = local_final_merge(date, category_views, atom_payload)
        final_report["merge_method"] = "deterministic_from_category_views"
    else:
        try:
            final_report = llm_final_merge(
                client,
                date=date,
                category_views=category_views,
                atom_payload=atom_payload,
                max_tokens=config.final_merge_max_tokens,
                retry_attempts=config.merge_retry_attempts,
            )
        except Exception as error:  # noqa: BLE001
            final_report = local_final_merge(date, category_views, atom_payload)
            final_report["merge_method"] = "local_after_llm_error"
            final_report["llm_error"] = clip(str(error), 500)

    full_payload = {
        "schemaVersion": 1,
        "generated_at": now_iso(),
        "date": date,
        "source": "all_report_summaries",
        "source_report_count": len(summaries),
        "category_count": len(category_views),
        "skip_llm": args.skip_llm,
        "detail_level": config.detail_level,
        "final_report": final_report,
        "category_views": category_views,
        "insight_atoms_path": str(atoms_path.relative_to(config.repo_root)),
    }
    json_path = state_dir / "stage1-4-full-daily-report.json"
    md_path = state_dir / "stage1-4-full-daily-report.md"
    knowledge_md_path = daily_dir / f"{date}-full-daily-report.md"
    markdown = render_markdown(date, final_report, category_views, atom_payload)
    write_json(json_path, full_payload)
    write_text(md_path, markdown)
    write_text(knowledge_md_path, markdown)

    print(str(json_path))
    print(str(atoms_path))
    print(str(knowledge_md_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
